install.packages("tidyverse")
install.packages("ggplot2")
install.packages("ggthemes")
install.packages("magrittr")
install.packages("dplyr")
install.packages("sf")
install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
install.packages("countrycode")
install.packages("ggrepel")

library("tidyverse")
library("ggplot2")
library("ggthemes")
library("magrittr")
library("dplyr")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("countrycode")
library("ggrepel")
library(readr)

unicef_metadata <- read_csv("unicef_metadata.csv")
unicef_indicator_1 <- read_csv("unicef_indicator_1.csv")
